### ISSUE TITLE
Readme?

### ISSUE THREAD

**Issue by L3P3** [ExoSkye/KusOS#1]
I love the fact you create public repos so others can be inspired by your work.
However, it is annoying to open a repo without having any idea what this is about.
So please, always create at least a tiny readme with at least one single sentence, explaining what and why.
You are welcome! :slightly_smiling_face:

**Comment by ExoSkye** [comment]
I tend to, by default, make my repositories public. These are still my personal projects. For example, this one is one that is in *very* early stage of development, as such, there is likely nothing of value here yet.
I don't completely understand why there is any need for a README for it as of right now. If/When it becomes something meaningful, I will add a README, as of right now, I see no need and I'd prefer to just work on my code.
